sonar.projectKey=dockerized-microservices-deployment
sonar.projectName=Dockerized Microservices Deployment
sonar.projectVersion=1.0.0

sonar.sources=backend/app,frontend/src
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12

sonar.exclusions=**/__pycache__/**,**/.venv/**,**/node_modules/**,helm/**,k8s/**
