apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ include "dockerized-microservices.namespace" . }}
  labels:
    {{- include "dockerized-microservices.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  POSTGRES_DB: {{ .Values.database.name | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%v/%s" .Values.database.user .Values.database.password .Values.postgres.service.name .Values.postgres.service.port .Values.database.name | quote }}
